version: '3.8'
services:
  db:
    image: docker.io/library/postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posdb
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/posdb
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    stdin_open: true  # keep stdin open for interactive console
    tty: true          # allocate a pseudo-TTY
    command: python -m src.cli
